### ISSUE TITLE
Traefik v3

### ISSUE THREAD

**Issue by jlandowner** [cosmo-workspace/cosmo#721]
This change may be affect us.

https://doc.traefik.io/traefik/master/migration/v2-to-v3/
> Kubernetes CRDs API Group traefik.containo.us
> In v3 the Kubernetes CRDs API Group traefik.containo.us has been removed. Please use the API Group traefik.io instead.

> Matchers
> In v3, the Headers and HeadersRegexp matchers have been renamed to Header and HeaderRegexp respectively.
> PathPrefix no longer uses regular expressions to match path prefixes.
> QueryRegexp has been introduced to match query values using a regular expression.
> HeaderRegexp, HostRegexp, PathRegexp, QueryRegexp, and HostSNIRegexp matchers now uses the [Go regexp syntax](https://golang.org/pkg/regexp/syntax/).
> All matchers now take a single value (except Header, HeaderRegexp, Query, and QueryRegexp which take two) and should be explicitly combined using logical operators to mimic previous behavior.
> Query can take a single value to match is the query value that has no value (e.g. /search?mobile).
> HostHeader has been removed, use Host instead.

**Comment by oruharo** [comment]
I think #721 is an Issue after Traefik v3 was released, do you want to Close it with this PR?

**Comment by jlandowner** [comment]
We completed all the tasks for this.
I think the rest is test to update dependencies as usual.
